In [2]:
import os as os


In [6]:
fuseq_folds = os.listdir("/Users/prksh/Downloads/MET_Eskip/FUSEQ-Satya/FUSEQ-Satya")
os.chdir("/Users/prksh/Downloads/MET_Eskip/FUSEQ-Satya/FUSEQ-Satya")

In [7]:
fuseq_folds

['VE4I_fusions',
 'VFML_fusions',
 'VGNF-F-CE-S30-L003_fusions',
 'VHCB-F2-CE-S58_fusions',
 'VITA-F-CE-S27_fusions',
 'VJ1I-F-CE-S54_fusions',
 'VJTC-F-CE-S10_fusions',
 'WA1I-F-D-LL2-CE-S50-L004_fusions',
 'WBFQ-F-D-CE-S72_fusions',
 'WEEB-F-D-CE-S134_fusions',
 'WEVH-F1F2-D-FEV2F2both-S33_fusions']

In [8]:
for dir in fuseq_folds:
    if 'feq_ALL.txt' in os.listdir(dir):
        
        os.rename(f'{dir}/feq_ALL.txt', f'{dir}/{dir}_feq_ALL.txt')

In [28]:
os.listdir('IN-HOM-WCAA-FE-S7_fusions')

['FuSeq_WES_MR_fge.txt',
 'FuSeq_WES_MR_fge_fdb.txt',
 'IN-HOM-WCAA-FE-S7-FuSeq_WES_FusionFinal.txt',
 'IN-HOM-WCAA-FE-S7-FuSeq_WES_SR_fge.txt',
 'IN-HOM-WCAA-FE-S7-FuSeq_WES_SR_fge_fdb.txt',
 'IN-HOM-WCAA-FE-S7_fusions_feq_ALL.txt',
 'splitReadInfo.bedpe',
 'splitReadInfo.txt']

In [3]:
os.chdir("/Users/prksh/Downloads/MET_Eskip/NegativeSams/feq_ALL_negs/")

In [4]:
import pandas as pd

In [13]:
neg_sams = os.listdir("/Users/prksh/Downloads/MET_Eskip/FUSEQ-Satya/FUSEQ-Satya/posiSams/")
os.chdir("/Users/prksh/Downloads/MET_Eskip//FUSEQ-Satya/FUSEQ-Satya/posiSams/")

In [14]:
import pandas as pd

In [15]:
for f in neg_sams:
    df = pd.read_csv(f, sep="\t")
    df2=df[df['Transcript'].str.contains("MET_")]
    if len(df2)>0:
        df2[['Gene', 'Chr', 'start', 'end']]=df2['Transcript'].str.split("__", expand =True)
        df2['start'] = df2['start'].astype(int)
        df2['end'] = df2['end'].astype(int)
        
        metski1=[]
        for i in df2['start']:
            if i in range(116411551,116417443):
                metski1.append('Skip Split')
            else:
                metski1.append('NS Split')
        metski2=[]
        for i in df2['end']:
            if i in range(116411551,116417443):
                metski2.append('Skip Split')
            else:
                metski2.append('NS Split')
        df2['start_skip'] = metski1
        df2['end_skip'] = metski2
        df2.sort_values(by='Transcript')
        df2['filename'] = f
        df2.to_csv(f'{f}_METskip.csv')
    
    
    


C:\Users\prksh\AppData\Local\Temp\ipykernel_26036\303876223.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2[['Gene', 'Chr', 'start', 'end']]=df2['Transcript'].str.split("__", expand =True)
C:\Users\prksh\AppData\Local\Temp\ipykernel_26036\303876223.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2[['Gene', 'Chr', 'start', 'end']]=df2['Transcript'].str.split("__", expand =True)
C:\Users\prksh\AppData\Local\Temp\ipykernel_26036\303876223.py:5: SettingWithCopyWarning: 
A value is trying to be set

In [65]:
df2=df[df['Transcript'].str.contains("MET_")]

In [ ]:
df2[['Gene', 'Chr', 'start', 'end']]=df2['Transcript'].str.split("__", expand =True)

In [ ]:
df2['start'] = df2['start'].astype(int)
df2['end'] = df2['end'].astype(int)

In [69]:
metski1=[]
for i in df2['start']:
    if i in range(116411551,116417443):
        metski1.append('Skip Split')
    else:
        metski1.append('NS Split')
 

metski2=[]
for i in df2['end']:
    if i in range(116411551,116417443):
        metski2.append('Skip Split')
    else:
        metski2.append('NS Split')


In [ ]:
df2['start_skip'] = metski1
df2['end_skip'] = metski2

In [ ]:
df2.sort_values(by='Transcript')

In [73]:
df['filename'] = 'vbuk'

In [74]:
df['filename']

0       vbuk
1       vbuk
2       vbuk
3       vbuk
4       vbuk
        ... 
5439    vbuk
5440    vbuk
5441    vbuk
5442    vbuk
5443    vbuk
Name: filename, Length: 5444, dtype: object

In [ ]:
'chr66'-'c'

In [ ]:
gene_name = "MET"
exon13_sequence = "ACGTGTACAGCTGACTGACTGACTGAC"
exon14_sequence = "TCGAGCTAGCTAGCTAGCTAGCTA"
exon15_sequence = "GTACAGCTGACTGACTGACTGACTGACGTACAG"

# Create a dictionary to store the splice variant sequences
splice_variants = {
    "Transcript1": exon13_sequence + exon14_sequence + exon15_sequence,
    "Transcript2": exon13_sequence + exon15_sequence,
    "Transcript3": exon13_sequence + exon14_sequence,
    # Add more splice variants if necessary
}

# Write the splice variant sequences to the reference FASTA file
with open(f"{gene_name}_reference.fasta", "w") as fasta_file:
    for transcript_id, sequence in splice_variants.items():
        fasta_file.write(f">{transcript_id}\n{sequence}\n")


In [ ]:
import pandas as pd
import os
import glob2
from pandas.errors import EmptyDataError 
path1= "/media/bioinfoa/bioinfo2/cluster_vcfs/transfer_vcf"
files= os.listdir(path1)
out_path="/media/bioinfoa/bioinfo2/cluster_vcfs/slice_vcf"
os.chdir(path1)
for file in files:
    try:
        vcf_file=pd.read_csv(file,sep='\t',comment='#',header=None)
        res_vcf=vcf_file[vcf_file[0]=='chr7']
        final_df13=res_vcf[(res_vcf[1]>=116411705) & (res_vcf[1] <= 116411711)]
        final_df14start=res_vcf[(res_vcf[1]>=116411900) & (res_vcf[1] <= 116411906)]
        final_df14=final_df14start.append(res_vcf[(res_vcf[1]>=116412040) & (res_vcf[1] <= 116412046)])
        final_df15=res_vcf[(res_vcf[1]>=116414932) & (res_vcf[1] <= 116414938)]
        if not final_df13.empty:
            file_name13= file+'_13.csv'
            file_name14= file+'_14.csv'
            file_name15 = file + '_15.csv'
            out_file13= os.path.join(out_path, file_name13)
            out_file14=os.path.join(out_path, file_name14)
            out_file15=os.path.join(out_path, file_name15)

            final_df13.to_csv(out_file13, index=False)
            final_df14.to_csv(out_file14, index=False)
            final_df15.to_csv(out_file15,index= False)

            
            del final_df13
            del final_df14
            del final_df15
    except EmptyDataError:
        continue

In [4]:
import numpy as np
print(np.sort(np.array(['Ram','Astha','Raghavendra'])))

['Astha' 'Raghavendra' 'Ram']


In [5]:
arr1 = np.array(['Ram','Astha','Brahat'])
arr2 = np.array(['Shyam','Kalyan','Naveen'])
arr1 > arr2

array([False, False, False])

In [6]:
x = np.array([-5, 9 , 20 , 25, -3, 5, 16, 10,-8])
x[(x >= -5) & (x <= 15)] *= -1 

In [ ]:
import pandas as pd
import os

input_path = "/media/bioinfoa/bioinfo2/cluster_vcfs/transfer_vcf"
output_path = "/media/bioinfoa/bioinfo2/cluster_vcfs/slice_vcf"

files = os.listdir(input_path)
os.chdir(input_path)

def process_file(file):
    try:
        vcf_file = pd.read_csv(file, sep='\t', comment='#', header=None)
        res_vcf = vcf_file[vcf_file[0] == 'chr7']
        
        regions = [
            (116411705, 116411711, '_13'),
            (116411900, 116411906, '_14'),
            (116412040, 116412046, '_14'),
            (116414932, 116414938, '_15')
        ]
        
        for start, end, suffix in regions:
            final_df = res_vcf[(res_vcf[1] >= start) & (res_vcf[1] <= end)]
            
            if not final_df.empty:
                file_name = file + suffix + '.csv'
                out_file = os.path.join(output_path, file_name)
                final_df.to_csv(out_file, index=False)
        
    except pd.errors.EmptyDataError:
        pass

for file in files:
    process_file(file)


In [ ]:
import pandas as pd
import os
import glob

output_path = "/media/bioinfoa/bioinfo2/cluster_vcfs/slice_vcf2"
merged_output_file = "/media/bioinfoa/bioinfo2/cluster_vcfs/merged_output.csv"

file_pattern = os.path.join(output_path, "*.csv")
file_list = glob.glob(file_pattern)

dfs = []
for file in file_list:
    df = pd.read_csv(file)
    filename = os.path.basename(file)
    df['Filename'] = filename
    dfs.append(df)

merged_df = pd.concat(dfs, ignore_index=True)
merged_df.to_csv(merged_output_file, index=False)


In [2]:
import numpy as np
x = np.array([-5, 9 , 20 , 25, -3, 5, 16, 10,-8])
x[(x >= -5) & (x <= 15)] *= -1 

In [3]:
x

array([  5,  -9,  20,  25,   3,  -5,  16, -10,  -8])

In [4]:
import numpy as np

a = np.arange(10,22).reshape((3, 4))

print(a)

[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]


In [5]:
import numpy as np
a = np.array([[6, 28], [8, 56], [7, 19]])
a

array([[ 6, 28],
       [ 8, 56],
       [ 7, 19]])

In [13]:
a.transpose().reshape(1,6)

array([[ 6,  8,  7, 28, 56, 19]])

## Improved Code including the hotspot regions

In [ ]:
regions = [
    (116411865, 116411890, '_hotspot'),
    (116411868, 116411886, '_hotspot'),
    (116411868, 116411903, '_hotspot'),
    (116411875, 116411889, '_hotspot'),
    (116411876, 116411897, '_hotspot'),
    (116411881, 116411901, '_hotspot'),
    (116411882, 116411898, '_hotspot'),
    (116411883, 116411902, '_hotspot'),
    (116411883, 116411904, '_hotspot'),
    (116411883, 116411954, '_hotspot'),
    (116411884, 116411900, '_hotspot'),
    (116411885, 116411895, '_hotspot'),
    (116411885, 116411896, '_hotspot'),
    (116411885, 116411901, '_hotspot'),
    (116411887, 116414938, '_hotspot'),
    (116411896, 116411935, '_hotspot'),
    (116411901, 116411930, '_hotspot'),
    (116411903, 116412043, '_hotspot'),
    (116411903, 116412043, '_hotspot'),
    (116411990, 116411990, '_hotspot'),
    (116411986, 116411986, '_hotspot'),
    (116411972, 116411972, '_hotspot'),
    (116411974, 116411974, '_hotspot'),
    (116411975, 116411975, '_hotspot'),
    (116411918, 116411918, '_hotspot'),
    (116411918, 116412110, '_hotspot'),
    (116411920, 116411955, '_hotspot'),
    (116412044, 116412044, '_hotspot'),
    (116412044, 116412044, '_hotspot'),
    (116412044, 116412044, '_hotspot'),
    (116412044, 116412044, '_hotspot'),
    (116412044, 116412044, '_hotspot'),
    (116412044, 116412052, '_hotspot'),
    (116412045, 116412045, '_hotspot'),
    (116412045, 116412045, '_hotspot')
]

import pandas as pd
import os

input_path = "/media/bioinfoa/bioinfo2/cluster_vcfs/transfer_vcf"
output_path = "/media/bioinfoa/bioinfo2/cluster_vcfs/slice_vcf"

files = os.listdir(input_path)
os.chdir(input_path)

def process_file(file):
    try:
        vcf_file = pd.read_csv(file, sep='\t', comment='#', header=None)
        res_vcf = vcf_file[vcf_file[0] == 'chr7']
        
        for start, end, suffix in regions:
            final_df = res_vcf[(res_vcf[1] >= start) & (res_vcf[1] <= end)]
            
            if not final_df.empty:
                file_name = file + suffix + '.csv'
                print(f'{file_name} - Done')
                out_file = os.path.join(output_path, file_name)
                final_df.to_csv(out_file, index=False)
        
    except pd.errors.EmptyDataError:
        pass

for file in files:
    process_file(file)


In [ ]:
bs upload dataset -p 389821433

In [5]:
# Define the boundary of MET exon 14
exon14_start = 116411903
exon14_end = 116412043

# Initialize variables
exon14_skipped = False
spliced_out_portion = 0.0
splice_junction_coordinates = ""

# Read the SJ.out.tab file
with open("/Users/prksh/Downloads/MET_Eskip/VEFD-F-ST8-S1_537689154.SJ.out.tab", "r") as file:
    for line in file:
        # Split the line into columns
        columns = line.strip().split("\t")
        
        # Extract relevant information
        contig = columns[0]
        splice_start = int(columns[1])
        print(splice_start)
        splice_end = int(columns[2])
        
        # Check if the splice junction involves MET exon 14
        if contig == "chr7" and exon14_start >= splice_start <= exon14_end and exon14_start <= splice_end <= exon14_end:
            exon14_skipped = True
            
            # Calculate the portion of exon 14 spliced out
            if splice_start <= exon14_start and splice_end >= exon14_end:
                spliced_out_portion = 1.0
            elif splice_start >= exon14_start and splice_end <= exon14_end:
                spliced_out_portion = (splice_end - splice_start + 1) / (exon14_end - exon14_start + 1)
            
            # Save the splice junction coordinates
            splice_junction_coordinates = f"{splice_start}-{splice_end}"
        
# Print the results
if exon14_skipped:
    print("MET exon 14 skipping detected.")
    print("Portion of exon 14 spliced out: {:.2%}".format(spliced_out_portion))
    print("Splice Junction Coordinates: " + splice_junction_coordinates)
else:
    print("MET exon 14 skipping not detected.")


310
795
962
1145
1820
2280
2516
2796
3323
3414
3631
7688
7722
8424
8473
9088
9119
10565
10722
10905
10925
11859
11940
13450
14056
14068
14068
14068
14378
15336
14830
16766
16766
16766
17056
17369
17369
17743
18062
18062
18367
18380
139697
164792
165943
172689
324061
700628
701768
708488
709661
709661
709661
741272
744004
880181
880181
880527
881034
881667
881926
883613
883984
886619
887520
887981
888669
889273
891394
891596
892654
896933
898298
899389
901995
902184
905804
907805
908391
909432
909745
915284
934994
935168
948957
955754
957843
970705
976261
976778
977083
977543
978838
979113
979404
979638
979820
980658
980904
981257
981469
981646
982116
982338
982835
983068
983276
983746
984440
984832
985176
985418
985710
985972
986218
986750
987026
987196
989932
989932
990340
1018368
1019764
1019887
1139349
1147519
1148085
1149166
1153069
1154014
1154308
1158738
1159349
1164327
1164327
1178027
1178294
1190868
1191506
1192511
1192691
1198767
1203373
1203373
1223217
1223418
1225769
1229314

In [6]:
# Define the boundary of MET exon 14
exon14_start = 116411903
exon14_end = 116412043

# Initialize variables
exon14_skipped = False
spliced_out_portion = 0.0
splice_junction_coordinates = ""

# Read the SJ.out.tab file
with open("/Users/prksh/Downloads/MET_Eskip/VEFD-F-ST8-S1_537689154.SJ.out.tab", "r") as file:
    for line in file:
        # Split the line into columns
        columns = line.strip().split("\t")
        
        # Extract relevant information
        contig = columns[0]
        splice_start = int(columns[1])
        splice_end = int(columns[2])
        
        # Check if the splice junction overlaps with MET exon 14
        if contig == "chr7" and ((exon14_start <= splice_start <= exon14_end) or (exon14_start <= splice_end <= exon14_end)):
            exon14_skipped = True
            
            # Calculate the portion of exon 14 spliced out
            if splice_start <= exon14_start and splice_end >= exon14_end:
                spliced_out_portion = 1.0
            elif splice_start >= exon14_start and splice_end <= exon14_end:
                spliced_out_portion = (splice_end - splice_start + 1) / (exon14_end - exon14_start + 1)
            
            # Save the splice junction coordinates
            splice_junction_coordinates = f"{splice_start}-{splice_end}"
        
# Print the results
if exon14_skipped:
    print("MET exon 14 skipping detected.")
    print("Portion of exon 14 spliced out: {:.2%}".format(spliced_out_portion))
    print("Splice Junction Coordinates: " + splice_junction_coordinates)
else:
    print("MET exon 14 skipping not detected.")


MET exon 14 skipping detected.
Portion of exon 14 spliced out: 0.00%
Splice Junction Coordinates: 116411709-116411912


In [7]:
# Define the boundary of MET exon 14
exon14_start = 116411903
exon14_end = 116412043

# Initialize variables
exon14_skipped = False
spliced_out_portions = []
splice_junction_coordinates = []

# Read the SJ.out.tab file
with open("/Users/prksh/Downloads/MET_Eskip/VEFD-F-ST8-S1_537689154.SJ.out.tab", "r") as file:
    for line in file:
        # Split the line into columns
        columns = line.strip().split("\t")
        
        # Extract relevant information
        contig = columns[0]
        splice_start = int(columns[1])
        splice_end = int(columns[2])
        
        # Check if the splice junction overlaps with MET exon 14
        if contig == "chr7" and ((exon14_start <= splice_start <= exon14_end) or (exon14_start <= splice_end <= exon14_end)):
            exon14_skipped = True
            
            # Calculate the portion of exon 14 spliced out
            if splice_start <= exon14_start and splice_end >= exon14_end:
                spliced_out_portion = 1.0
            elif splice_start >= exon14_start and splice_end <= exon14_end:
                spliced_out_portion = (splice_end - splice_start + 1) / (exon14_end - exon14_start + 1)
            else:
                intersection_start = max(splice_start, exon14_start)
                intersection_end = min(splice_end, exon14_end)
                spliced_out_portion = (intersection_end - intersection_start + 1) / (exon14_end - exon14_start + 1)
            
            # Save the splice junction coordinates and spliced out portion
            splice_junction_coordinates.append(f"{splice_start}-{splice_end}")
            spliced_out_portions.append(spliced_out_portion)
        
# Print the results
if exon14_skipped:
    print("MET exon 14 skipping detected in multiple hits.")
    for i in range(len(splice_junction_coordinates)):
        print("Hit", i+1)
        print("Portion of exon 14 spliced out: {:.2%}".format(spliced_out_portions[i]))
        print("Splice Junction Coordinates: " + splice_junction_coordinates[i])
        print()
else:
    print("MET exon 14 skipping not detected.")


MET exon 14 skipping detected in multiple hits.
Hit 1
Portion of exon 14 spliced out: 7.09%
Splice Junction Coordinates: 116411709-116411912



In [8]:
# Define the boundary of MET exon 14
exon14_start = 116411903
exon14_end = 116412043

# Initialize variables
hits = 0
exon14_skipped = False
spliced_out_portions = []
splice_junction_coordinates = []

# Read the SJ.out.tab file
with open("/Users/prksh/Downloads/MET_Eskip/VEFD-F-ST8-S1_537689154.SJ.out.tab", "r") as file:
    for line in file:
        # Split the line into columns
        columns = line.strip().split("\t")
        
        # Extract relevant information
        contig = columns[0]
        splice_start = int(columns[1])
        splice_end = int(columns[2])
        
        # Check if the splice junction overlaps with MET exon 14
        if contig == "chr7" and ((exon14_start <= splice_start <= exon14_end) or (exon14_start <= splice_end <= exon14_end)):
            hits += 1
            exon14_skipped = True
            
            # Calculate the portion of exon 14 spliced out
            if splice_start <= exon14_start and splice_end >= exon14_end:
                spliced_out_portion = 1.0
            elif splice_start >= exon14_start and splice_end <= exon14_end:
                spliced_out_portion = (splice_end - splice_start + 1) / (exon14_end - exon14_start + 1)
            else:
                intersection_start = max(splice_start, exon14_start)
                intersection_end = min(splice_end, exon14_end)
                spliced_out_portion = (intersection_end - intersection_start + 1) / (exon14_end - exon14_start + 1)
            
            # Save the splice junction coordinates and spliced out portion
            splice_junction_coordinates.append(f"{splice_start}-{splice_end}")
            spliced_out_portions.append(spliced_out_portion)
        
# Print the results
if exon14_skipped:
    if hits > 1:
        print("MET exon 14 skipping detected in multiple hits.")
    else:
        print("MET exon 14 skipping detected in a single hit.")
    
    for i in range(len(splice_junction_coordinates)):
        print("Hit", i+1)
        print("Portion of exon 14 spliced out: {:.2%}".format(spliced_out_portions[i]))
        print("Splice Junction Coordinates: " + splice_junction_coordinates[i])
        print()
else:
    print("MET exon 14 skipping not detected.")


MET exon 14 skipping detected in a single hit.
Hit 1
Portion of exon 14 spliced out: 7.09%
Splice Junction Coordinates: 116411709-116411912



In [19]:
# Define the boundary of MET exon 14
exon14_start = 116411903
exon14_end = 116412043


# Parse command-line arguments
import argparse
parser = argparse.ArgumentParser(description="Detect MET exon 14 skipping.")
parser.add_argument("-i", "--input", type=str, help="Input SJ file path")
args = parser.parse_args()


# Initialize variables
exon14_skipped = False
spliced_out_portions = []
splice_junction_coordinates = []

# Read the SJ.out.tab file
with open(args.input, "r") as file:
    for line in file:
        # Split the line into columns
        columns = line.strip().split("\t")
        
        # Extract relevant information
        contig = columns[0]
        splice_start = int(columns[1])
        splice_end = int(columns[2])
        
        # Check if the splice junction overlaps with MET exon 14
        if contig == "chr7" and ((exon14_start <= splice_start <= exon14_end) or (exon14_start <= splice_end <= exon14_end) or (splice_start <= exon14_start and splice_end >= exon14_end)):
        
            exon14_skipped = True
            
            # Calculate the portion of exon 14 spliced out
            if splice_start <= exon14_start and splice_end >= exon14_end:
                spliced_out_portion = 1.0
            elif splice_start >= exon14_start and splice_end <= exon14_end:
                spliced_out_portion = (splice_end - splice_start + 1) / (exon14_end - exon14_start + 1)
            else:
                intersection_start = max(splice_start, exon14_start)
                intersection_end = min(splice_end, exon14_end)
                spliced_out_portion = (intersection_end - intersection_start + 1) / (exon14_end - exon14_start + 1)
            
            # Save the splice junction coordinates and spliced out portion
            splice_junction_coordinates.append(f"{splice_start}-{splice_end}")
            spliced_out_portions.append(spliced_out_portion)
        
# Print the results
if exon14_skipped:
    if len(splice_junction_coordinates) > 1:
        print("MET exon 14 skipping detected in multiple hits.")
    else:
        print("MET exon 14 skipping detected in a single hit.")
    
    for i in range(len(splice_junction_coordinates)):
        print("Hit", i+1)
        print("Portion of exon 14 spliced out: {:.2%}".format(spliced_out_portions[i]))
        print("Splice Junction Coordinates: " + splice_junction_coordinates[i])
        print()
else:
    print("MET exon 14 skipping not detected.")


MET exon 14 skipping not detected.
